DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS riders_exits;
DROP TABLE IF EXISTS stages;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS riders_from;
DROP TABLE IF EXISTS riders;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS countries;
