CREATE TABLE IF NOT EXISTS countries (
  code    CHAR(3)        PRIMARY KEY,
  name    VARCHAR(64)    UNIQUE NOT NULL,
  region  VARCHAR(64)    NOT NULL
);

CREATE TABLE IF NOT EXISTS teams (
  name    VARCHAR(64)    PRIMARY KEY,
  country CHAR(3)        NOT NULL 
    REFERENCES countries (code) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS riders (
  bib     INTEGER       PRIMARY KEY,
  name    VARCHAR(64)   NOT NULL,
  dob     DATE          NOT NULL,
  team    VARCHAR(64)   NOT NULL 
    REFERENCES teams (name) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS riders_from (
  rider     INTEGER    PRIMARY KEY 
    REFERENCES riders (bib) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  country   CHAR(3)    NOT NULL 
    REFERENCES countries (code) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS locations (
  name      VARCHAR(64)   PRIMARY KEY,
  country   CHAR(3)       NOT NULL 
    REFERENCES countries (code) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS stages (
  num       INTEGER       PRIMARY KEY,
  day       DATE          UNIQUE NOT NULL,
  start     VARCHAR(64)   NOT NULL 
    REFERENCES locations (name) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  finish    VARCHAR(64)   NOT NULL 
    REFERENCES locations (name) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  length    INTEGER       NOT NULL
    CHECK (length > 0),
  type      VARCHAR(32)   NOT NULL 
    CHECK (type IN ('flat', 'hilly', 'mountain', 'individual time-trial', 'team time-trial'))
);

CREATE TABLE IF NOT EXISTS riders_exits (
  rider     INTEGER       PRIMARY KEY 
    REFERENCES riders (bib) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  stage     INTEGER       NOT NULL 
    REFERENCES stages (num) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  reason    VARCHAR(64)   NOT NULL 
    CHECK (reason IN ('withdrawal', 'DNS'))
);

CREATE TABLE IF NOT EXISTS results (
  rider     INTEGER     NOT NULL 
    REFERENCES riders (bib) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  stage     INTEGER     NOT NULL
    REFERENCES stages (num) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  rank      INTEGER     NOT NULL
    CHECK (rank > 0),
  time      INTEGER     NOT NULL 
    CHECK (time > 0),
  bonus     INTEGER     NOT NULL DEFAULT 0 
    CHECK (bonus >= 0),
  penalty   INTEGER     NOT NULL DEFAULT 0 
    CHECK (penalty >= 0),

  PRIMARY KEY(stage, rank)
);

