    DROP TABLE IF EXISTS Rider_Exit;
    DROP TABLE IF EXISTS Result;
    DROP TABLE IF EXISTS Stage;
    DROP TABLE IF EXISTS Location;
    DROP TABLE IF EXISTS Rider;
    DROP TABLE IF EXISTS Team;
    DROP TABLE IF EXISTS Country;
    DROP TABLE IF EXISTS Region;